### ISSUE TITLE
running projects results in time parsing error

### ISSUE THREAD

**Issue by jedi4ever** [jszwedko/circleci-cli#3] opened 2016-07-24 12:59 UTC
`circleci-cli projects` results in 

`parsing time "null" as ""2006-01-02T15:04:05Z07:00"": cannot parse "null" as """``

Other commands work fine

**Comment by jszwedko** [comment] 2016-07-31 18:58
Hi @jedi4ever,

Apologies for the delay. If you are stilling having this issue, could you navigate to https://circleci.com/api/v1/projects?circle-token=XXXXX and paste the JSON output here? It looks like one of the date fields is returning an unexpected value, but it is difficult to tell which one without the JSON it is trying to parse (which changes depending on the user logged in).

**Comment by jszwedko** [comment] 2016-07-31 19:00
It looks like there has been some chatter around adding the actual field name to the `encoding/json` error messages (https://go-review.googlesource.com/#/c/18692/) which would help with debugging this sort of issue in the future.

**Comment by jszwedko** [comment] 2016-08-30 03:04
Closing this since I cannot reproduce, but please reopen if you can provide the JSON being provided by CircleCI's API.

**Closed by jszwedko** 2016-08-30 03:04 UTC

**Comment by jszwedko** [comment] 2016-09-14 04:13
Hi @jedi4ever,

Not sure if this is still an issue for you, but I released a prerelease (https://github.com/jszwedko/circleci-cli/releases/tag/0.2.0-pre) that will give better error messages (including the field it failed to deserialize) if you wanted to try it and let me know what error it gives you.
